# This is a pre-commit configuration file that runs forge test
# before every commit and prevents the commit from happening if any test fails.

repos:
  - repo: local
    hooks:
      - id: forge-test
        name: forge test
        entry: forge test
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: name-tests-test
