[profile.default]
src = 'contracts'
test = 'test'
no_match_test = "testMock"
out = 'out'
libs = ['lib']
solc = "0.8.20"
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./"}]
[fmt] 
line_length = 100
[fuzz]
runs = 1000
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "http://localhost:8545"
[etherscan]
sepolia = { key = "QY37SBRGTHG35SV1455P6UF9CS8CKVB6QQ", url = "https://api-sepolia.etherscan.io/api" }
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }