#!/bin/sh

# Run all the tests using forge test
forge test

# Check the exit status of the previous command
if [ $? -eq 0 ]; then
  # If it is zero, print a success message
  echo "All tests passed."
else
  # If it is not zero, print a failure message
  echo "Some tests failed."
	exit 1
fi
